// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bot_state.sql

package sqlc

import (
	"context"
)

const getUpdateCursor = `-- name: GetUpdateCursor :one
SELECT id, update_id, updated_at FROM bot_update_cursor WHERE id = 1
`

func (q *Queries) GetUpdateCursor(ctx context.Context) (BotUpdateCursor, error) {
	row := q.db.QueryRowContext(ctx, getUpdateCursor)
	var i BotUpdateCursor
	err := row.Scan(&i.ID, &i.UpdateID, &i.UpdatedAt)
	return i, err
}

const upsertUpdateCursor = `-- name: UpsertUpdateCursor :exec
INSERT INTO bot_update_cursor (id, update_id) VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET update_id = excluded.update_id, updated_at = datetime('now')
`

func (q *Queries) UpsertUpdateCursor(ctx context.Context, updateID int64) error {
	_, err := q.db.ExecContext(ctx, upsertUpdateCursor, updateID)
	return err
}
