// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package sqlc

import (
	"context"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (room_code, phase) VALUES (?, ?) RETURNING id
`

type CreateGameParams struct {
	RoomCode string `json:"room_code"`
	Phase    string `json:"phase"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createGame, arg.RoomCode, arg.Phase)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertGamePlayer = `-- name: InsertGamePlayer :exec
INSERT INTO game_players (game_id, user_id, seat, role) VALUES (?, ?, ?, ?)
`

type InsertGamePlayerParams struct {
	GameID int64  `json:"game_id"`
	UserID int64  `json:"user_id"`
	Seat   int64  `json:"seat"`
	Role   string `json:"role"`
}

func (q *Queries) InsertGamePlayer(ctx context.Context, arg InsertGamePlayerParams) error {
	_, err := q.db.ExecContext(ctx, insertGamePlayer,
		arg.GameID,
		arg.UserID,
		arg.Seat,
		arg.Role,
	)
	return err
}
