// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package sqlc

import (
	"context"
)

const getMediaCache = `-- name: GetMediaCache :one
SELECT cache_key, file_id, file_type, created_at FROM media_cache WHERE cache_key = ?
`

func (q *Queries) GetMediaCache(ctx context.Context, cacheKey string) (MediaCache, error) {
	row := q.db.QueryRowContext(ctx, getMediaCache, cacheKey)
	var i MediaCache
	err := row.Scan(
		&i.CacheKey,
		&i.FileID,
		&i.FileType,
		&i.CreatedAt,
	)
	return i, err
}

const upsertMediaCache = `-- name: UpsertMediaCache :exec
INSERT INTO media_cache (cache_key, file_id, file_type) VALUES (?, ?, ?)
ON CONFLICT(cache_key) DO UPDATE SET file_id = excluded.file_id, file_type = excluded.file_type
`

type UpsertMediaCacheParams struct {
	CacheKey string `json:"cache_key"`
	FileID   string `json:"file_id"`
	FileType string `json:"file_type"`
}

func (q *Queries) UpsertMediaCache(ctx context.Context, arg UpsertMediaCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertMediaCache, arg.CacheKey, arg.FileID, arg.FileType)
	return err
}
