// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type BattleReport struct {
	ID        int64  `json:"id"`
	GameID    int64  `json:"game_id"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
}

type BotUpdateCursor struct {
	ID        int64  `json:"id"`
	UpdateID  int64  `json:"update_id"`
	UpdatedAt string `json:"updated_at"`
}

type Game struct {
	ID         int64          `json:"id"`
	RoomCode   string         `json:"room_code"`
	Phase      string         `json:"phase"`
	WinnerCamp sql.NullString `json:"winner_camp"`
	Aborted    int64          `json:"aborted"`
	SettledAt  string         `json:"settled_at"`
}

type GamePlayer struct {
	GameID   int64  `json:"game_id"`
	UserID   int64  `json:"user_id"`
	Seat     int64  `json:"seat"`
	Role     string `json:"role"`
	IsWinner int64  `json:"is_winner"`
}

type MediaCache struct {
	CacheKey  string `json:"cache_key"`
	FileID    string `json:"file_id"`
	FileType  string `json:"file_type"`
	CreatedAt string `json:"created_at"`
}

type RoleStat struct {
	UserID int64  `json:"user_id"`
	Role   string `json:"role"`
	Wins   int64  `json:"wins"`
	Losses int64  `json:"losses"`
	Plays  int64  `json:"plays"`
}

type Room struct {
	RoomCode   string         `json:"room_code"`
	HostUserID int64          `json:"host_user_id"`
	Phase      string         `json:"phase"`
	CreatedAt  string         `json:"created_at"`
	StartedAt  sql.NullString `json:"started_at"`
}

type RoomPlayer struct {
	RoomCode string `json:"room_code"`
	UserID   int64  `json:"user_id"`
	Seat     int64  `json:"seat"`
	IsHost   int64  `json:"is_host"`
	JoinedAt string `json:"joined_at"`
}

type RoomSetting struct {
	RoomCode     string `json:"room_code"`
	Settings     string `json:"settings"`
	PasswordHash string `json:"password_hash"`
}

type User struct {
	TelegramID int64  `json:"telegram_id"`
	Nickname   string `json:"nickname"`
	CreatedAt  string `json:"created_at"`
}
