// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateGame(ctx context.Context, arg CreateGameParams) (int64, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) error
	DeleteRoom(ctx context.Context, roomCode string) error
	GetMediaCache(ctx context.Context, cacheKey string) (MediaCache, error)
	GetRoleStats(ctx context.Context, userID int64) ([]RoleStat, error)
	GetRoomByCode(ctx context.Context, roomCode string) (Room, error)
	GetUpdateCursor(ctx context.Context) (BotUpdateCursor, error)
	GetUser(ctx context.Context, telegramID int64) (User, error)
	InsertBattleReport(ctx context.Context, arg InsertBattleReportParams) error
	InsertGamePlayer(ctx context.Context, arg InsertGamePlayerParams) error
	InsertRoomPlayer(ctx context.Context, arg InsertRoomPlayerParams) error
	ListActiveRooms(ctx context.Context) ([]Room, error)
	UpsertMediaCache(ctx context.Context, arg UpsertMediaCacheParams) error
	UpsertRoleStat(ctx context.Context, arg UpsertRoleStatParams) error
	UpsertUpdateCursor(ctx context.Context, updateID int64) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
