// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlc

import (
	"context"
)

const getRoleStats = `-- name: GetRoleStats :many
SELECT user_id, role, wins, losses, plays FROM role_stats WHERE user_id = ? ORDER BY role
`

func (q *Queries) GetRoleStats(ctx context.Context, userID int64) ([]RoleStat, error) {
	rows, err := q.db.QueryContext(ctx, getRoleStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleStat{}
	for rows.Next() {
		var i RoleStat
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.Wins,
			&i.Losses,
			&i.Plays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBattleReport = `-- name: InsertBattleReport :exec
INSERT INTO battle_reports (game_id, content) VALUES (?, ?)
`

type InsertBattleReportParams struct {
	GameID  int64  `json:"game_id"`
	Content string `json:"content"`
}

func (q *Queries) InsertBattleReport(ctx context.Context, arg InsertBattleReportParams) error {
	_, err := q.db.ExecContext(ctx, insertBattleReport, arg.GameID, arg.Content)
	return err
}

const upsertRoleStat = `-- name: UpsertRoleStat :exec
INSERT INTO role_stats (user_id, role, wins, losses, plays) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(user_id, role) DO UPDATE SET wins = excluded.wins, losses = excluded.losses, plays = excluded.plays
`

type UpsertRoleStatParams struct {
	UserID int64  `json:"user_id"`
	Role   string `json:"role"`
	Wins   int64  `json:"wins"`
	Losses int64  `json:"losses"`
	Plays  int64  `json:"plays"`
}

func (q *Queries) UpsertRoleStat(ctx context.Context, arg UpsertRoleStatParams) error {
	_, err := q.db.ExecContext(ctx, upsertRoleStat,
		arg.UserID,
		arg.Role,
		arg.Wins,
		arg.Losses,
		arg.Plays,
	)
	return err
}
