// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package sqlc

import (
	"context"
)

const createRoom = `-- name: CreateRoom :exec
INSERT INTO rooms (room_code, host_user_id, phase) VALUES (?, ?, ?)
`

type CreateRoomParams struct {
	RoomCode   string `json:"room_code"`
	HostUserID int64  `json:"host_user_id"`
	Phase      string `json:"phase"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.ExecContext(ctx, createRoom, arg.RoomCode, arg.HostUserID, arg.Phase)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE room_code = ?
`

func (q *Queries) DeleteRoom(ctx context.Context, roomCode string) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, roomCode)
	return err
}

const getRoomByCode = `-- name: GetRoomByCode :one
SELECT room_code, host_user_id, phase, created_at, started_at FROM rooms WHERE room_code = ?
`

func (q *Queries) GetRoomByCode(ctx context.Context, roomCode string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByCode, roomCode)
	var i Room
	err := row.Scan(
		&i.RoomCode,
		&i.HostUserID,
		&i.Phase,
		&i.CreatedAt,
		&i.StartedAt,
	)
	return i, err
}

const getRoomSettings = `-- name: GetRoomSettings :one
SELECT settings, password_hash FROM room_settings WHERE room_code = ?
`

type GetRoomSettingsRow struct {
	Settings     string `json:"settings"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) GetRoomSettings(ctx context.Context, roomCode string) (GetRoomSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getRoomSettings, roomCode)
	var i GetRoomSettingsRow
	err := row.Scan(&i.Settings, &i.PasswordHash)
	return i, err
}

const insertRoomPlayer = `-- name: InsertRoomPlayer :exec
INSERT INTO room_players (room_code, user_id, seat, is_host) VALUES (?, ?, ?, ?)
`

type InsertRoomPlayerParams struct {
	RoomCode string `json:"room_code"`
	UserID   int64  `json:"user_id"`
	Seat     int64  `json:"seat"`
	IsHost   int64  `json:"is_host"`
}

func (q *Queries) InsertRoomPlayer(ctx context.Context, arg InsertRoomPlayerParams) error {
	_, err := q.db.ExecContext(ctx, insertRoomPlayer,
		arg.RoomCode,
		arg.UserID,
		arg.Seat,
		arg.IsHost,
	)
	return err
}

const listActiveRooms = `-- name: ListActiveRooms :many
SELECT room_code, host_user_id, phase, created_at, started_at FROM rooms ORDER BY created_at, room_code
`

func (q *Queries) ListActiveRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.RoomCode,
			&i.HostUserID,
			&i.Phase,
			&i.CreatedAt,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRoomSettings = `-- name: UpsertRoomSettings :exec
INSERT INTO room_settings (room_code, settings, password_hash) VALUES (?, ?, ?)
ON CONFLICT(room_code) DO UPDATE SET settings = excluded.settings, password_hash = excluded.password_hash
`

type UpsertRoomSettingsParams struct {
	RoomCode     string `json:"room_code"`
	Settings     string `json:"settings"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpsertRoomSettings(ctx context.Context, arg UpsertRoomSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertRoomSettings, arg.RoomCode, arg.Settings, arg.PasswordHash)
	return err
}
