// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT telegram_id, nickname, created_at FROM users WHERE telegram_id = ?
`

func (q *Queries) GetUser(ctx context.Context, telegramID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, telegramID)
	var i User
	err := row.Scan(&i.TelegramID, &i.Nickname, &i.CreatedAt)
	return i, err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (telegram_id, nickname) VALUES (?, ?)
ON CONFLICT(telegram_id) DO UPDATE SET nickname = excluded.nickname
`

type UpsertUserParams struct {
	TelegramID int64  `json:"telegram_id"`
	Nickname   string `json:"nickname"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser, arg.TelegramID, arg.Nickname)
	return err
}
